import type { EnhanceAppContext } from 'vitepress'
import VPArtPlayer from './VPArtPlayer.vue'
import VPVideoEmbed from './VPVideoEmbed.vue'

export { VPArtPlayer, VPVideoEmbed }

/**
 * Register the video plugin's Vue components (`VPArtPlayer` and `VPVideoEmbed`)
 * globally on the VitePress application instance.
 *
 * 在 VitePress 应用实例上全局注册视频插件的 Vue 组件
 * （`VPArtPlayer` 与 `VPVideoEmbed`）。
 *
 * Invoked automatically by the `virtual:enhance-app` module generated by
 * `vitepress-tuck` when the plugin is enabled.
 *
 * 当插件启用时，由 `vitepress-tuck` 生成的 `virtual:enhance-app` 虚拟模块
 * 自动调用。
 */
export function enhanceAppWithVideo({ app }: EnhanceAppContext) {
  app.component('VPArtPlayer', VPArtPlayer)
  app.component('VPVideoEmbed', VPVideoEmbed)
}
