import type { EnhanceAppContext } from 'vitepress/client'
import VPQrcode from './VPQrcode.vue'

export { VPQrcode }
export * from './types.js'
export * from './use-qrcode.js'

/**
 * Registers the `VPQrcode` component globally during VitePress app
 * initialization.
 *
 * 在 VitePress 应用初始化期间全局注册 `VPQrcode` 组件。
 *
 * This function is referenced by the plugin's `client.enhance` field and is
 * invoked automatically by the `virtual:enhance-app` module generated by
 * `vitepress-tuck`.
 *
 * 该函数由插件的 `client.enhance` 字段引用，并由 `vitepress-tuck` 生成的
 * `virtual:enhance-app` 模块自动调用。
 *
 * @param param0 - The VitePress enhance app context / VitePress 应用增强上下文
 * @param param0.app - The Vue application instance to register the component on / 要注册组件的 Vue 应用实例
 * @example
 * `.vitepress/theme/index.ts`
 * ```ts
 * import { defineEnhanceApp } from 'vitepress-tuck/client'
 * import { enhanceAppWithQrcode } from 'vitepress-plugin-qrcode/client'
 *
 * export default {
 *   enhanceApp(ctx) {
 *     enhanceAppWithQrcode(ctx)
 *   },
 * }
 * ```
 */
export function enhanceAppWithQrcode({ app }: EnhanceAppContext) {
  app.component('VPQrcode', VPQrcode)
}
